In [4]:
import numpy as np

In [5]:
airplanes = np.array([20,120,140,20,440,600,340])

In [6]:
airplanes

array([ 20, 120, 140,  20, 440, 600, 340])

In [7]:
airplanes.size

7

In [9]:
airplanes.shape

(7,)

In [11]:
#has start, stop, step. don't specify then it is just a stop
#use this for numbers which are not integers
pricechart = np.arange(2.5,27,2.5)

In [12]:
pricechart

array([  2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5,  25. ])

In [13]:
airplanes + airplanes

array([  40,  240,  280,   40,  880, 1200,  680])

In [14]:
airplanes + pricechart

ValueError: operands could not be broadcast together with shapes (7,) (10,) 

In [16]:
numbers1 = np.arange(10)
numbers2 = np.arange(5)
numbers1 + np.concatenate([numbers2, numbers2])

array([ 0,  2,  4,  6,  8,  5,  7,  9, 11, 13])

In [19]:
%timeit -n 10000 [x**2 for x in range(10)]

10000 loops, best of 3: 5.3 µs per loop


In [21]:
%timeit -n 10000 np.arange(10)**2

10000 loops, best of 3: 2.44 µs per loop


In [22]:
myarray = np.arange(10)

In [23]:
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
odd = myarray[1::2] #start at 1 and take every second item
even = myarray[0::2] #start at 0 and take every second item - also [::2]
print(odd)
print(even)

[1 3 5 7 9]
[0 2 4 6 8]


In [26]:
np.multiply(np.concatenate((odd,even)), myarray)

array([ 0,  3, 10, 21, 36,  0, 12, 28, 48, 72])