In [1]:
import numpy as np
Sales = np.loadtxt('LemonadeStand.csv', delimiter = ",")

In [2]:
Sales

array([[ 653.11,  168.  ],
       [ 960.32,  132.  ],
       [ 339.57,  162.  ],
       [  17.72,   45.  ],
       [ 125.06,  177.  ],
       [ 526.6 ,   84.  ],
       [ 676.59,  197.  ],
       [  59.93,  158.  ],
       [ 238.72,   72.  ],
       [ 749.2 ,  164.  ],
       [ 505.4 ,  188.  ],
       [  52.88,  146.  ],
       [ 149.28,   10.  ],
       [ 312.62,   23.  ],
       [ 337.1 ,  139.  ],
       [ 201.05,   76.  ]])

In [3]:
RowItem=Sales.T

In [4]:
RowItem

array([[ 653.11,  960.32,  339.57,   17.72,  125.06,  526.6 ,  676.59,
          59.93,  238.72,  749.2 ,  505.4 ,   52.88,  149.28,  312.62,
         337.1 ,  201.05],
       [ 168.  ,  132.  ,  162.  ,   45.  ,  177.  ,   84.  ,  197.  ,
         158.  ,   72.  ,  164.  ,  188.  ,  146.  ,   10.  ,   23.  ,
         139.  ,   76.  ]])

In [5]:
RowItem[0]

array([ 653.11,  960.32,  339.57,   17.72,  125.06,  526.6 ,  676.59,
         59.93,  238.72,  749.2 ,  505.4 ,   52.88,  149.28,  312.62,
        337.1 ,  201.05])

In [6]:
RowItem[1]

array([ 168.,  132.,  162.,   45.,  177.,   84.,  197.,  158.,   72.,
        164.,  188.,  146.,   10.,   23.,  139.,   76.])

In [25]:
Sales.sum()

7846.1499999999996

In [21]:
round(Sales.mean(),2)

245.19

In [9]:
Sales.min()

10.0

In [10]:
Sales.max()

960.32000000000005

In [11]:
DaySales = RowItem[0] + RowItem[1]
DaySales

array([  821.11,  1092.32,   501.57,    62.72,   302.06,   610.6 ,
         873.59,   217.93,   310.72,   913.2 ,   693.4 ,   198.88,
         159.28,   335.62,   476.1 ,   277.05])

In [13]:
bonus = np.where(DaySales > 500, 20 + .05 * DaySales, .05* DaySales )

In [14]:
bonus

array([ 61.0555,  74.616 ,  45.0785,   3.136 ,  15.103 ,  50.53  ,
        63.6795,  10.8965,  15.536 ,  65.66  ,  54.67  ,   9.944 ,
         7.964 ,  16.781 ,  23.805 ,  13.8525])

In [19]:
bonus.round().sum()

535.0

In [32]:
bonus.sum()

532.30999999999995

In [47]:
payroll = np.array(['Bess', 'Nancy', 'George','Bess', 'Nancy', 'George','Bess', 'Nancy', 'George','Bess', 'Nancy', 'George','Bess', 'Nancy', 'George','Bess'])

In [48]:
BessPay = np.where(payroll == 'Bess', 1, 0)
NancyPay = np.where(payroll == 'Nancy', 1, 0)
GeorgePay = np.where(payroll == "George", 1, 0)

In [49]:
payroll

array(['Bess', 'Nancy', 'George', 'Bess', 'Nancy', 'George', 'Bess',
       'Nancy', 'George', 'Bess', 'Nancy', 'George', 'Bess', 'Nancy',
       'George', 'Bess'], 
      dtype='<U6')

In [50]:
BessPay

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1])

In [57]:
BessSal = bonus * BessPay
NancySal = bonus * NancyPay
GeorgeSal = bonus * GeorgePay

In [61]:
BessSal

array([ 61.0555,   0.    ,   0.    ,   3.136 ,   0.    ,   0.    ,
        63.6795,   0.    ,   0.    ,  65.66  ,   0.    ,   0.    ,
         7.964 ,   0.    ,   0.    ,  13.8525])

In [58]:
print("Bess: ", BessSal.sum())
print("Nancy: ", NancySal.sum())
print("George: ", GeorgeSal.sum())


Bess:  215.3475
Nancy:  172.0665
George:  5492.28051925


In [65]:
PayRoll = np.array([BessSal, NancySal, GeorgeSal])

In [66]:
PayRoll

array([[   61.0555    ,     0.        ,     0.        ,     3.136     ,
            0.        ,     0.        ,    63.6795    ,     0.        ,
            0.        ,    65.66      ,     0.        ,     0.        ,
            7.964     ,     0.        ,     0.        ,    13.8525    ],
       [    0.        ,    74.616     ,     0.        ,     0.        ,
           15.103     ,     0.        ,     0.        ,    10.8965    ,
            0.        ,     0.        ,    54.67      ,     0.        ,
            0.        ,    16.781     ,     0.        ,     0.        ],
       [    0.        ,     0.        ,  2032.07116225,     0.        ,
            0.        ,  2553.2809    ,     0.        ,     0.        ,
          241.367296  ,     0.        ,     0.        ,    98.883136  ,
            0.        ,     0.        ,   566.678025  ,     0.        ]])

In [69]:
a = np.array([1,2,3])
b = np.array([10,9,8])
ab = np.array([a,b])

In [70]:
ab


array([[ 1,  2,  3],
       [10,  9,  8]])

In [71]:
np.save('PayRoll', PayRoll)