In [1]:
import numpy as np
week2 = np.array([
    [340, 280, 0],
    [340,40,240],
    [480,360,540],
    [240,480,420],
    [460,300,40],
    [140,300,40],
    [300,60,420]
])

In [3]:
week2.T

array([[340, 340, 480, 240, 460, 140, 300],
       [280,  40, 360, 480, 300, 300,  60],
       [  0, 240, 540, 420,  40,  40, 420]])

In [4]:
week2.shape

(7, 3)

In [5]:
week3 = np.array([[[300,10], [240,10], [480,8]],
                 [[140,15], [240,30], [300,10]],
                 [[480,8], [460,20], [270,5]]])

In [6]:
week3

array([[[300,  10],
        [240,  10],
        [480,   8]],

       [[140,  15],
        [240,  30],
        [300,  10]],

       [[480,   8],
        [460,  20],
        [270,   5]]])

In [7]:
week3[2,1,0]

460

In [9]:
np.cos(46)

-0.43217794488477829

In [10]:
sticks = week3[:,:,1]

In [11]:
sticks

array([[10, 10,  8],
       [15, 30, 10],
       [ 8, 20,  5]])

In [12]:
pricechart = np.arange(2.5,27,2.5)
pricechart

array([  2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5,  25. ])

In [14]:
np.floor(pricechart)
np.ceil(pricechart)
np.power(pricechart, 8.3)

array([  2.00863984e+03,   6.33068983e+05,   1.83235023e+07,
         1.99526231e+08,   1.27160758e+09,   5.77507263e+09,
         2.07594481e+10,   6.28852749e+10,   1.67153279e+11,
         4.00776337e+11])