In [1]:
import numpy as np
numbers1 = np.arange(10)
numbers2 = np.arange(5)

In [2]:
numbers1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
numbers2

array([0, 1, 2, 3, 4])

In [12]:
numbers1 + numbers2

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [4]:
numbers1 * numbers1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
numbers1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
np.sum(numbers1)

45

In [7]:
np.average(numbers1)

4.5

In [8]:
np.mean(numbers1)

4.5

In [9]:
numbers1.size
numbers1[::2]
#numbers2 = numbers1(0,numbers1.size-1,2)
#numbers2

array([0, 2, 4, 6, 8])

In [10]:
odd = numbers1[1::2]
even = numbers1[::2]

In [13]:
np.multiply(np.concatenate((odd, even)), numbers1)

array([ 0,  3, 10, 21, 36,  0, 12, 28, 48, 72])

In [19]:
workers = [['Nancy', 'parttime', .35,.5], ['George', 'parttime', .25,.6]]
import pandas as pd
workerdf = pd.DataFrame(workers, 
                        columns = ['Name', 'Status', 'Commission', 'StickMaking'])
workerdf

Name    Status  Commission  StickMaking
0   Nancy  parttime        0.35          0.5
1  George  parttime        0.25          0.6

In [22]:
workerdf.append({'Name': 'Bess', 'Status': 'parttime', 'Commission':.25, 'StickMaking':.6}, ignore_index = True)

Name    Status  Commission  StickMaking
0   Nancy  parttime        0.35          0.5
1  George  parttime        0.25          0.6
2    Bess  parttime        0.25          0.6

In [24]:
workerdf

Name    Status  Commission  StickMaking
0   Nancy  parttime        0.35          0.5
1  George  parttime        0.25          0.6