In [1]:
import numpy as np
airplanes = np.array([20,120,140,20,440,600,340])

In [2]:
airplanes

array([ 20, 120, 140,  20, 440, 600, 340])

In [3]:
np.size(airplanes)

7

In [4]:
airplanes.ndim

1

In [5]:
airplanes.dtype

dtype('int32')

In [6]:
airplanes.size

7

In [7]:
airplanes.shape

(7,)

In [8]:
count = np.arange(10)

In [9]:
count

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
priceChart = np.arange(2.5, 27, 2.5)

In [11]:
priceChart


array([  2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5,  25. ])

In [12]:
priceChart.dtype

dtype('float64')

In [66]:
np.ceil(priceChart)

array([  3.,   5.,   8.,  10.,  13.,  15.,  18.,  20.,  23.,  25.])

In [67]:
np.power(priceChart, 1.5)

array([   3.95284708,   11.18033989,   20.53959591,   31.6227766 ,
         44.19417382,   58.09475019,   73.20775232,   89.4427191 ,
        106.72687103,  125.        ])

In [13]:
airplanes + airplanes

array([  40,  240,  280,   40,  880, 1200,  680])

In [14]:
airplanes * 9

array([ 180, 1080, 1260,  180, 3960, 5400, 3060])

In [15]:
airplanes[4:7]

array([440, 600, 340])

In [16]:
airplanes[-3]

440

In [17]:
airplanes[::-1]

array([340, 600, 440,  20, 140, 120,  20])

In [18]:
week2 = np.array([
    [340,280,0],
    [340,40,240],
    [480,360,540],
    [240,480,420],
    [460,300,40],
    [140,300,40],
    [300,60,420]
])

In [19]:
week2

array([[340, 280,   0],
       [340,  40, 240],
       [480, 360, 540],
       [240, 480, 420],
       [460, 300,  40],
       [140, 300,  40],
       [300,  60, 420]])

In [64]:
week2.sum()

5820

In [63]:
week2.sum(axis = 0)

array([2300, 1820, 1700])

In [56]:
week2.sum(axis = 1)

array([ 620,  620, 1380, 1140,  800,  480,  780])

In [20]:
week3 = np.array([[[300, 10], [240,10], [480,8]], 
                  [[140, 15],[240, 30],[300,10]],
                  [[480, 8],[460,20], [270,5]]])

In [21]:
week3

array([[[300,  10],
        [240,  10],
        [480,   8]],

       [[140,  15],
        [240,  30],
        [300,  10]],

       [[480,   8],
        [460,  20],
        [270,   5]]])

In [22]:
week3.size

18

In [23]:
week3.ndim


3

In [24]:
week3.size

18

In [25]:
np.size(week3, 0)

3

In [26]:
np.size(week3, 1)

3

In [27]:
np.size(week3, 2)

2

In [28]:
week3.dtype

dtype('int32')

In [29]:
week3.shape

(3, 3, 2)

In [30]:
week3[2]

array([[480,   8],
       [460,  20],
       [270,   5]])

In [31]:
week3[:,2]

array([[480,   8],
       [300,  10],
       [270,   5]])

In [32]:
week3[2,1,0]

460

In [33]:
week3[::,0]

array([[300,  10],
       [140,  15],
       [480,   8]])

In [34]:
week3[::,1]

array([[240,  10],
       [240,  30],
       [460,  20]])

In [35]:
week3[2,2,1]

5

In [36]:
week3[::,2]

array([[480,   8],
       [300,  10],
       [270,   5]])

In [37]:
week3[:2]

array([[[300,  10],
        [240,  10],
        [480,   8]],

       [[140,  15],
        [240,  30],
        [300,  10]]])

In [38]:
week3[:,:,1]

array([[10, 10,  8],
       [15, 30, 10],
       [ 8, 20,  5]])

In [39]:
week2.T

array([[340, 340, 480, 240, 460, 140, 300],
       [280,  40, 360, 480, 300, 300,  60],
       [  0, 240, 540, 420,  40,  40, 420]])

In [40]:
np.save('StickTrial', week3)

In [41]:
np.savetxt('week2_text', week2, delimiter = ",")

In [42]:
week3


array([[[300,  10],
        [240,  10],
        [480,   8]],

       [[140,  15],
        [240,  30],
        [300,  10]],

       [[480,   8],
        [460,  20],
        [270,   5]]])

In [43]:
sticks = week3[:,:,1]

In [44]:
sticks

array([[10, 10,  8],
       [15, 30, 10],
       [ 8, 20,  5]])

In [45]:
prize = np.where(sticks > 13, 1, 0)

In [46]:
prize


array([[0, 0, 0],
       [1, 1, 0],
       [0, 1, 0]])

In [47]:
prize.cumsum()

array([0, 0, 0, 1, 2, 2, 2, 3, 3], dtype=int32)

In [48]:
prize.sum()

3

In [69]:
#work week of a specific employee
workWeek2 = ([1,0,0],
             [0,1,0],
             [0,0,0],
             [1,0,0],
             [0,1,0],
             [0,0,0],
             [1,0,0])
workWeek2

([1, 0, 0], [0, 1, 0], [0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 0], [1, 0, 0])

In [50]:
payFor = workWeek2 * week2
payFor

array([[340,   0,   0],
       [  0,  40,   0],
       [  0,   0,   0],
       [240,   0,   0],
       [  0, 300,   0],
       [  0,   0,   0],
       [300,   0,   0]])

In [51]:
payFor.sum() * .25

305.0

In [70]:
payFor.dropna()

AttributeError: 'numpy.ndarray' object has no attribute 'dropna'